name : Build_OVEP

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - '**'  # Triggers on a PR to any branch

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4  #checkout to your repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the setup-python action
      with:
       python-version: '3.10'

    - name: Download OepnVINO
      run: |
        curl -L -o openvino.zip https://storage.openvinotoolkit.org/repositories/openvino/packages/2024.3/windows/w_openvino_toolkit_windows_2024.3.0.16041.1e3b88e4e3f_x86_64.zip
        Expand-Archive -Path openvino.zip -DestinationPath openvino_folder

    - name: Build Openvino Execution Provider
      run: |
        cd openvino_folder
        cd w_openvino_toolkit_windows_2024.3.0.16041.1e3b88e4e3f_x86_64
        call setupvars.bat
        cd ../../
        call build.bat --build --update --config Release --cmake_generator "Visual Studio 17 2022" --use_openvino --build_shared_lib --skip_tests --parallel  --compile_no_warning_as_error
      shell: cmd
