name : Trigger Internal ci

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - '**'  # Triggers on a PR to any branch

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD_SOURCESDIRECTORY: ${{ github.workspace }}
      BUILD_BINARIESDIRECTORY: ${{ github.workspace }}/build
    steps:
    - uses: actions/checkout@v4  #checkout to your repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the setup-python action
      with:
       python-version: '3.10'

    - name: Create build directory
      run: |
         mkdir -p ${{ env.BUILD_BINARIESDIRECTORY }}
         chmod -R 777 ${{ env.BUILD_BINARIESDIRECTORY }}

    - name: Running Internal CI
      run: |
        cd tools/ci_build/github/linux/
        dir
        ./run_dockerbuild.sh -o ubuntu22.04 -p 3.10 -d openvino -v 2024.3.0 -x "--config RelWithDebInfo --use_openvino CPU --build_wheel --build_shared_lib --parallel --enable_pybind --skip_onnx_tests"
      shell: bash
